import { Roboto } from 'next/font/google'
import './globals.css'
import HeaderComp from '../components/layout/Header'
import dbConnect from '../utils/db'
// import dbConnect from '@utils/db'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  await dbConnect();

  return (
    <html lang="en">
      <body
        className={roboto.className}>
        <HeaderComp />
        <main className='max-w-4xl mx-auto p-4'>
          {children}
        </main>
      </body>
    </html>
  )
}
